// Builds the WASM module (wasm-pack, web target) and generates the inline-base64 loader module.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, '..');
const repo = resolve(pkg, '..', '..');

if (!process.env.QS_SKIP_WASM_PACK) {
  execFileSync(
    'wasm-pack',
    ['build', 'bindings/wasm', '--target', 'web', '--release', '--out-dir', '../../packages/quantum-safe-ts/wasm',
     '--out-name', 'quantum_safe_wasm', '--no-pack'],
    { cwd: repo, stdio: 'inherit', shell: process.platform === 'win32' },
  );
}

// wasm-bindgen's glue falls back to `new URL('quantum_safe_wasm_bg.wasm', import.meta.url)` when no
// source is given. We always pass the bytes/module explicitly, but bundlers (Vite, webpack) see that
// expression statically and emit a second, unused copy of the .wasm. Replace it with an error.
const gluePath = resolve(pkg, 'wasm', 'quantum_safe_wasm.js');
let glue = readFileSync(gluePath, 'utf8');
const marker = "new URL('quantum_safe_wasm_bg.wasm', import.meta.url)";
if (glue.includes(marker)) {
  glue = glue.replace(marker, "(() => { throw new Error('quantum-safe-ts: no WASM source was provided; call init()'); })()");
  writeFileSync(gluePath, glue);
  console.log('patched wasm-bindgen glue: removed implicit .wasm URL');
} else if (!glue.includes('no WASM source was provided')) {
  throw new Error('wasm-bindgen glue layout changed; update scripts/build-wasm.mjs');
}

const wasm = readFileSync(resolve(pkg, 'wasm', 'quantum_safe_wasm_bg.wasm'));
mkdirSync(resolve(pkg, 'src'), { recursive: true });
writeFileSync(
  resolve(pkg, 'src', 'wasm-inline.generated.ts'),
  `// AUTO-GENERATED by scripts/build-wasm.mjs. Do not edit.\nexport const WASM_BASE64 = ${JSON.stringify(wasm.toString('base64'))};\n`,
);
console.log(`WASM ${wasm.length} bytes embedded as base64 (${Math.round((wasm.length * 4) / 3)} chars)`);
