// Builds the WASM module (wasm-pack, web target) and generates the inline-base64 loader module.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, '..');
const repo = resolve(pkg, '..', '..');

if (!process.env.QS_SKIP_WASM_PACK) {
  execFileSync(
    'wasm-pack',
    ['build', 'bindings/wasm', '--target', 'web', '--release', '--out-dir', '../../packages/quantum-safe-ts/wasm',
     '--out-name', 'quantum_safe_wasm', '--no-pack'],
    { cwd: repo, stdio: 'inherit', shell: process.platform === 'win32' },
  );
}

const wasm = readFileSync(resolve(pkg, 'wasm', 'quantum_safe_wasm_bg.wasm'));
mkdirSync(resolve(pkg, 'src'), { recursive: true });
writeFileSync(
  resolve(pkg, 'src', 'wasm-inline.generated.ts'),
  `// AUTO-GENERATED by scripts/build-wasm.mjs. Do not edit.\nexport const WASM_BASE64 = ${JSON.stringify(wasm.toString('base64'))};\n`,
);
console.log(`WASM ${wasm.length} bytes embedded as base64 (${Math.round((wasm.length * 4) / 3)} chars)`);
