import { existsSync, readFileSync } from 'node:fs';
import { defineConfig } from 'vitepress';

// The API reference is generated by TypeDoc (`npm run api`) from the library's own doc comments.
const apiSidebar = existsSync(new URL('../api/typedoc-sidebar.json', import.meta.url))
  ? JSON.parse(readFileSync(new URL('../api/typedoc-sidebar.json', import.meta.url), 'utf8'))
  : [];

export default defineConfig({
  title: 'quantum-safe-ts',
  description: 'Hybrid post-quantum cryptography for TypeScript and JavaScript.',
  base: process.env.DOCS_BASE ?? '/quantum-safe-ts/',
  cleanUrls: true,
  lastUpdated: false,
  head: [['meta', { name: 'robots', content: 'index, follow' }]],
  themeConfig: {
    search: { provider: 'local' },
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Cookbook', link: '/guide/cookbook' },
      { text: 'API', link: '/api/' },
      { text: 'Tools', link: '/tools/audit' },
      { text: 'Choose a library', link: '/compare' },
      { text: 'Roadmap', link: 'https://github.com/AnimeshShaw/quantum-safe-ts/blob/master/ROADMAP.md' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Start',
          items: [
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Quick start recipes', link: '/guide/quick-start' },
            { text: 'Choosing what to use', link: '/guide/choosing' },
            { text: 'Concepts', link: '/guide/concepts' },
            { text: 'Runtimes and bundlers', link: '/guide/runtimes' },
          ],
        },
        {
          text: 'Features',
          items: [
            { text: 'Key encapsulation and hybrids', link: '/guide/kem' },
            { text: 'Encryption (envelopes)', link: '/guide/encryption' },
            { text: 'Signatures', link: '/guide/signatures' },
            { text: 'Streaming encryption', link: '/guide/streaming' },
            { text: 'JWT', link: '/guide/jwt' },
            { text: 'Keys and passwords', link: '/guide/keys' },
          ],
        },
        {
          text: 'Guides',
          items: [
            { text: 'Cookbook', link: '/guide/cookbook' },
            { text: 'Migrating to post-quantum', link: '/guide/migration' },
            { text: 'Interop with quantum-safe-py', link: '/guide/python-interop' },
            { text: 'CNSA 2.0 and standards', link: '/guide/standards' },
          ],
        },
        {
          text: 'Reference and help',
          items: [
            { text: 'Errors', link: '/guide/errors' },
            { text: 'Security model', link: '/guide/security' },
            { text: 'Upgrading and compatibility', link: '/guide/upgrading' },
            { text: 'Troubleshooting and FAQ', link: '/guide/faq' },
            { text: 'Glossary', link: '/guide/glossary' },
            { text: 'Roadmap', link: 'https://github.com/AnimeshShaw/quantum-safe-ts/blob/master/ROADMAP.md' },
          ],
        },
      ],
      '/tools/': [
        {
          text: 'Tools',
          items: [
            { text: 'quantum-safe-audit', link: '/tools/audit' },
            { text: 'GitHub Action', link: '/tools/github-action' },
            { text: 'MCP server for agents', link: '/tools/mcp' },
          ],
        },
      ],
      '/api/': apiSidebar,
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/AnimeshShaw/quantum-safe-ts' }],
    footer: {
      message: 'Apache-2.0.',
    },
  },
});
