#!/usr/bin/env python3
"""Extract the RFC 8554 Appendix F test cases (HSS/LMS/LM-OTS, SHA-256) into tests/vectors/lms_rfc8554.json.

    python scripts/extract_rfc8554_vectors.py [path/to/rfc8554.txt]

If no path is given the RFC is downloaded from rfc-editor.org. The vectors come straight from the RFC text:
nothing here is generated by this project's own code.
"""
import json
import pathlib
import re
import sys
import urllib.request

root = pathlib.Path(__file__).resolve().parent.parent
if len(sys.argv) > 1:
    text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
else:
    with urllib.request.urlopen("https://www.rfc-editor.org/rfc/rfc8554.txt", timeout=60) as r:
        text = r.read().decode("utf-8")
lines = text.splitlines()

LABELED = re.compile(r"^ {3}[A-Za-z][\w\[\]\. ]*?\s{2,}([0-9a-f]+)\s*(?:#.*)?$")
CONT = re.compile(r"^ {10,}([0-9a-f]+)\s*(?:#.*)?$")
MSG_LABELED = re.compile(r"^ {3}Message\s+((?:[0-9a-f]{2} ?)+)\s*\|")
MSG_CONT = re.compile(r"^ {10,}((?:[0-9a-f]{2} ?)+)\s*\|")


def section(title: str, end_markers) -> list[str]:
    start = next(i for i, l in enumerate(lines) if l.strip() == title)
    out = []
    for l in lines[start + 1 :]:
        if any(l.strip().startswith(m) for m in end_markers):
            break
        if l.startswith("McGrew") or l.startswith("RFC 8554"):
            continue
        out.append(l)
    return out


def hex_fields(block: list[str]) -> str:
    out = ""
    for l in block:
        m = LABELED.match(l) or CONT.match(l)
        if m:
            out += m.group(m.lastindex)
    return out


def message(block: list[str]) -> str:
    out = ""
    for l in block:
        m = MSG_LABELED.match(l) or MSG_CONT.match(l)
        if m:
            out += m.group(1).replace(" ", "")
    return out


cases = []
for n in (1, 2):
    nxt = f"Test Case {n + 1}" if n == 1 else "Appendix G"
    pub = hex_fields(section(f"Test Case {n} Public Key", [f"Test Case {n} Message"]))
    msg = message(section(f"Test Case {n} Message", [f"Test Case {n} Signature"]))
    ends = ["Test Case 2 Private Key"] if n == 1 else ["Appendix G", "G.  "]
    sig = hex_fields(section(f"Test Case {n} Signature", ends + ["Authors' Addresses"]))
    cases.append({"name": f"RFC 8554 Appendix F test case {n}", "hss_public_key": pub, "message": msg, "hss_signature": sig})

for c in cases:
    print(c["name"], "pk", len(c["hss_public_key"]) // 2, "msg", len(c["message"]) // 2, "sig", len(c["hss_signature"]) // 2)
out = root / "tests" / "vectors" / "lms_rfc8554.json"
out.write_text(json.dumps({"source": "https://www.rfc-editor.org/rfc/rfc8554.txt Appendix F", "cases": cases}, indent=1) + "\n")
print("wrote", out)
